# Generated by Django 5.1 on 2024-09-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_column='status_field', default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at_field', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at_field', verbose_name='Updated at')),
                ('from_user', models.ForeignKey(db_column='from_user_field', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='From User')),
                ('to_user', models.ForeignKey(db_column='to_user_field', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='To User')),
            ],
            options={
                'db_table': 'friendship',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
