# Generated by Django 5.1 on 2024-08-28 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_field', max_length=30, null=True, verbose_name='Name')),
                ('email', models.EmailField(db_column='user_email', db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(db_column='active_status', default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_column='staff_status', default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_column='super_user', default=False, verbose_name='Is SuperUser')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
